/*
 * Copyright 2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.paoloantinori.qea.plugin.report;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Renders {@link IgnoreRecommendation}s as ready-to-paste XML snippets for maven-dependency-plugin's
 * {@code analyze} goal and for DepClean, per TASK-3 plan item 2. Formats verified against the two
 * plugins' own sources rather than guessed:
 *
 * <ul>
 *   <li><b>maven-dependency-plugin</b>: {@code <ignoredUnusedDeclaredDependencies>} of
 *       {@code <ignoredUnusedDeclaredDependency>} entries (confirmed against
 *       {@code https://maven.apache.org/plugins/maven-dependency-plugin/examples/exclude-dependencies-from-dependency-analysis.html}
 *       and the {@code analyze-mojo.html} parameter reference). The filter syntax is
 *       {@code [groupId]:[artifactId]:[type]:[version]}; every segment is optional and a missing
 *       trailing segment is an implicit wildcard, so a bare {@code groupId:artifactId} already
 *       ignores that dependency at any type/version. Not a regex: no escaping needed.</li>
 *   <li><b>DepClean</b>: {@code <ignoreDependencies>} of {@code <ignoreDependency>} entries
 *       (child element name follows the sibling maven-dependency-plugin convention and Maven's
 *       collection-parameter binding, which accepts any child tag for a {@code Set<String>}
 *       parameter -- confirmed against {@code depclean-maven-plugin}'s {@code DepCleanMojo}
 *       source, {@code @Parameter Set<String> ignoreDependencies}). Each entry is a Java regex,
 *       compiled case-insensitively and matched with {@code Matcher#matches()} (full string, not
 *       {@code find()}) against {@code groupId:artifactId:version:scope} (confirmed against
 *       {@code DepCleanManager#toDependency} and {@code Dependency#toString} in depclean-core).
 *       Literal dots in the GA must be escaped: an unescaped {@code .} is regex "any character",
 *       so e.g. {@code io.quarkus} would also match {@code ioXquarkus}.</li>
 * </ul>
 */
// Hand-rolled XML (not Xpp3Dom/plexus-utils) by design: pulling plexus-utils in for this alone would
// make it a used-undeclared transitive dependency (the exact anti-pattern this project exists to
// fight), Xpp3Dom cannot render the explanatory comment headers below, and escapeXml is unit-tested.
public final class IgnoreFragments {

    /** File name written under the project build directory when {@code -Dqea.ignoreFragments=true}. */
    public static final String MAVEN_DEPENDENCY_PLUGIN_FILE_NAME = "qea-mdp-ignores.xml";

    /** File name written under the project build directory when {@code -Dqea.ignoreFragments=true}. */
    public static final String DEPCLEAN_FILE_NAME = "qea-depclean-ignores.xml";

    private IgnoreFragments() {
    }

    public static String mavenDependencyPluginFragment(List<IgnoreRecommendation> recommendations) {
        StringBuilder sb = new StringBuilder();
        sb.append("<!-- Generated by quarkus-extension-analyzer: paste inside maven-dependency-plugin's\n")
                .append("     analyze goal <configuration>. Covers used-config/used-capability extensions only;\n")
                .append("     see the JSON report's ignoreRecommendations for the full evidence trail. -->\n");
        sb.append("<ignoredUnusedDeclaredDependencies>\n");
        for (IgnoreRecommendation r : recommendations) {
            sb.append("  <ignoredUnusedDeclaredDependency>").append(escapeXml(r.ga()))
                    .append("</ignoredUnusedDeclaredDependency>\n");
        }
        sb.append("</ignoredUnusedDeclaredDependencies>\n");
        return sb.toString();
    }

    public static String depCleanFragment(List<IgnoreRecommendation> recommendations) {
        StringBuilder sb = new StringBuilder();
        sb.append("<!-- Generated by quarkus-extension-analyzer: paste inside depclean-maven-plugin's\n")
                .append("     <configuration>. Entries are regexes matched against groupId:artifactId:version:scope;\n")
                .append("     covers used-config/used-capability extensions only. -->\n");
        sb.append("<ignoreDependencies>\n");
        for (IgnoreRecommendation r : recommendations) {
            sb.append("  <ignoreDependency>").append(escapeXml(depCleanRegex(r.ga())))
                    .append("</ignoreDependency>\n");
        }
        sb.append("</ignoreDependencies>\n");
        return sb.toString();
    }

    /**
     * Writes both fragments under {@code buildDir} (the project's build/target directory), returning
     * the paths written, in the order MDP then DepClean.
     */
    public static List<Path> writeFragments(List<IgnoreRecommendation> recommendations, Path buildDir)
            throws IOException {
        Files.createDirectories(buildDir);
        Path mdp = buildDir.resolve(MAVEN_DEPENDENCY_PLUGIN_FILE_NAME);
        Path depClean = buildDir.resolve(DEPCLEAN_FILE_NAME);
        Files.writeString(mdp, mavenDependencyPluginFragment(recommendations));
        Files.writeString(depClean, depCleanFragment(recommendations));
        List<Path> written = new ArrayList<>();
        written.add(mdp);
        written.add(depClean);
        return written;
    }

    /**
     * {@code groupId:artifactId} with literal dots escaped, plus a {@code :.*} suffix wildcarding the
     * version and scope segments that DepClean's full-string match otherwise requires accounting for.
     */
    static String depCleanRegex(String ga) {
        return ga.replace(".", "\\.") + ":.*";
    }

    static String escapeXml(String value) {
        return value.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&apos;");
    }
}
